### PR TITLE
add support barometer height

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Review by maaikelimper — CHANGES_REQUESTED** [review]
Hi Tom, I tried to test but the result does not seem right:
```
root@45980a1e5dc1:/home/wis2box# wis2box metadata station get 0-20000-0-97780
[2023-09-07T14:35:06Z] {/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py:135} INFO - Searching for stations
ENAROTALI,0-20000-0-97780,97780,landFixed,-3.9166666667,136.3666666667,1770.0,IDN,V
```

vs the original result:
`ENAROTALI,0-20000-0-97780,97780,Land (fixed),-3.926791,136.378213,,Indonesia,V`

Could you please check ?

**Comment by maaikelimper** [comment]
Giving a valid station that is not Land (fixed) will cause the command to crash, for example:
```
root@45980a1e5dc1:/home/wis2box# wis2box metadata station get 0-22000-0-1900024
[2023-09-07T14:40:51Z] {/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py:135} INFO - Searching for stations
Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 11, in <module>
    load_entry_point('wis2box', 'console_scripts', 'wis2box')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/wis2box/metadata/station.py", line 333, in get
    station = client.get_station_report(wsi, format_='XML', summary=True)
  File "/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py", line 241, in get_station_report
    return self.get_station_report_summary(response)
  File "/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py", line 276, in get_station_report_summary
    wmo_region = get_xpath(
  File "/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py", line 428, in get_xpath
    value = value[0]
IndexError: list index out of range
```

**Comment by maaikelimper** [comment]
KeyError on 'latitude' for 0-20000-0-74002 
```
root@45980a1e5dc1:/home/wis2box# wis2box metadata station get 0-20000-0-74002
[2023-09-07T15:55:21Z] {/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py:135} INFO - Searching for stations
Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 11, in <module>
    load_entry_point('wis2box', 'console_scripts', 'wis2box')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/wis2box/metadata/station.py", line 340, in get
    'latitude': station['latitude'],
KeyError: 'latitude'
```

**Comment by maaikelimper** [comment]
KeyError: 'antarctica' on 0-20000-0-89628
```
root@45980a1e5dc1:/home/wis2box# wis2box metadata station get 0-20000-0-89628
[2023-09-07T16:04:58Z] {/usr/local/lib/python3.8/dist-packages/pyoscar/__init__.py:135} INFO - Searching for stations
Traceback (most recent call last):
  File "/app/wis2box/metadata/station.py", line 347, in get
    results['wmo_region'] = WMO_RAS[station['wmo_region']]
KeyError: 'antarctica'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 11, in <module>
    load_entry_point('wis2box', 'console_scripts', 'wis2box')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/wis2box/metadata/station.py", line 349, in get
    results['wmo_region'] = WMDR_RAS[station['wmo_region']]
KeyError: 'antarctica'
```

**Comment by tomkralidis** [comment]
> 0-20000-0-97780

This is because the code now looks for facility geometry.  If none is found, then we try to derive elevation from the process/equipment (along with the corresponding latitude/longitude).

**Comment by tomkralidis** [comment]
@maaikelimper the abovementioned issues should now be addressed; some results if not found will yield an empty "column" on stdout.  Note that wis2box-management needs to be rebuilt to reflect the associated updates in pyoscar (new version) and wis2box station metadata code.  Testing/feedback is most valued.

**Comment by maaikelimper** [comment]
I ran a couple of tests using stations provided previously but results don't look right. There is still the 3-letter code inside of name of tounctry, lat/lon are should be retrieved from station-location not instrument, the station in Antartica has no region-code ?
```
root@e3f0dad30806:/home/wis2box# wis2box metadata station get  0-20000-0-74002
"ABERDEEN PROVING GROUNDS, MD.",0-20000-0-74002,74002,Land (fixed),,,,USA,IV
root@e3f0dad30806:/home/wis2box# wis2box metadata station get  0-20000-0-78108
"ABRAHAM'S BAY, MAYAGUANA",0-20000-0-78108,78108,Land (fixed),,,,BHS,IV
root@e3f0dad30806:/home/wis2box# wis2box metadata station get  0-20000-0-89628
AGO-1,0-20000-0-89628,89628,Land (fixed),-83.8666666667,129.6166666667,2865.0,USA,
root@e3f0dad30806:/home/wis2box# wis2box metadata station get  0-20000-0-97780
ENAROTALI,0-20000-0-97780,97780,Land (fixed),-3.9166666667,136.3666666667,1770.0,IDN,V
```
I double-checked that pyoscar got updated to 0.6.1:
```
root@e3f0dad30806:/home/wis2box# pip3 freeze | grep pyoscar
pyoscar==0.6.1
```

**Comment by maaikelimper** [comment]
We also miss  barometer_height. Maybe we could table this issue until we review the status of the station-metadata-form Dave is working on?

**Comment by maaikelimper** [comment]
I can still crash it by providing a station without a valid country, for example:
`wis2box metadata station get 0-22000-0-6101028`

**Review by maaikelimper — APPROVED** [review]

**Pull request merged**
