### PR TITLE
adhere to WIS2 Message Format Schema

### PR DESCRIPTION
**Pull request by maaikelimper**
adhere to WIS2 Message Format Schema, could this still make it into the 0.5.0 release

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @maaikelimper.  I'm not sure if `base64` is allowed for `properties.content.encoding`?  From the [specification](https://github.com/wmo-im/wis2-notification-message/blob/main/WIS2_Message_Format_README.adoc):

Table 4. Detail of the <strong>content</strong> array

Key | Value(s) | Example | Status | Description
-- | -- | -- | -- | --
encoding | utf-8 | utf-8 | Mandatory | If provided the data MUST be encoded in UTF-8.

cc @golfvert

**Comment by tomkralidis** [comment]
In addition, the specification does not have `size`, but `length`.

**Comment by maaikelimper** [comment]
The definition of the WIS2-message format was supposed to be define by:
https://github.com/wmo-im/wis2-notification-message/blob/main/WIS2_Message_Format_Schema.yaml

This has the following for "content"

``` 
     content:
        type: object
        description: Used to embed small products inline within the message.
        properties:
          encoding:
            type: string
            description: encoding of content
            enum:
              - utf-8
              - base64
          size:
            type: integer
            description: Number of bytes contained in the file. Together with the ``integrity`` property, it provides additional assurance that file content was accurately received.
            # RGiraud: Can we limit the size of the embedded data here?
          value:
            type: string
            description: the inline content of the file.
        required:
          - encoding
          - size
   ```

**Comment by maaikelimper** [comment]
The documentation mentions that 'content' is only meant when sharing the data inside the message and the 'size' should be less than 2048. So for larger files the WIS2-notification-schema has no property to define the size. Could/should we add a 'size'-property independent of the 'content' ?

**Comment by golfvert** [comment]
When in "content" we have the `length` key (not size). It make sense to add an optional key `size` in the properties.

**Comment by tomkralidis** [comment]
The [OGC link schema](https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/schemas/link.yaml) already has an optional `length` property in the link object which we can reuse.

**Comment by tomkralidis** [comment]
Based on discussion/updates with @golfvert for the notification message:

- `properties.content.size` remains (mandatory)
- `links[*].length` remains (optional)
- if `properties.content` is specified, then ALL of its child elements are mandatory.  In the wis2box case we are not inlining any data currently.  As a result we should not include `properties.content`, and instead specify `links[0].length` instead

**Comment by maaikelimper** [comment]
Using links{*}.length is perfect for me, that makes a lot more sense in wis2box as we don't use the content-block for data atm. I've updated the PR. 

I also threw out examples/scripts/python-mqp-subscribe.py as it was using the outdated format. wis2box will refer to pywis-pubsub in the near future instead.

**Review by tomkralidis — APPROVED** [review]

**Pull request merged**
