### PR TITLE
update to Elasticsearch 8 and latest pygeoapi, add wis2box-ui-admin

### PR DESCRIPTION
**Pull request by tomkralidis**
In support of #154 

- updates to ES8
- updates based on latest pygeoapi (https://github.com/wmo-im/wis2box-api/pull/25)
- adds editable endpoints for metadata resources (metadata UI)
  - POST/PUT/DELETE commands on `/oapi/collections/discovery-metadata` and `/oapi/collections/stations` will need admin auth

❗❗❗  Note: this is a breaking change❗❗❗

Users will need to clear their ES data with:

```bash
docker volume rm wis2box_project_es-data
docker volume rm wis2box_project_api-config
```

...before installing the forthcoming 1.0.b2 release.

As an alternative workaround, from the elasticsearch container:
```bash
curl -XDELETE http://localhost:9200/discovery-metadata
curl -XDELETE http://localhost:9200/stations
```

...however we would have to verify that the observations are intact with the ES 7-> ES 8 upgrade.

The above will need to be added to the release notes.

### CODE REVIEW

**Comment by tomkralidis** [comment]
Add steps to release notes, including design time steps to generate discovery/station metadata.

**Comment by maaikelimper** [comment]
I've tried to test es-8 on wis2box-italy:
- I added 'apt-get update -y' to wis2box-management Dockeerfile to allow the build to succeed (404 during install packages in wis2box-management otherwise)
- I got the error "error.message":"cannot upgrade a node from version [7.16.2] directly to version [8.6.2], upgrade to version [7.17.0] first.","error.stack_trace":"java.lang.IllegalStateException: cannot upgrade a node from version [7.16.2] directly to version [8.6.2], upgrade to version [7.17.0]
- I changed elasticsearch image to 7.17.0, started wis2box check all was ok, then stopped wis2box
- I changed elasticsearch image back to 8.6.2, restarted wis2box all data is still there
- I checked elasticsearch-log and found this error: "error.message":"not all primary shards of [.geoip_databases] index are active" However it appears non-fatal as the wis2box-services are all running?
- I also noted the following warning in elasticsearch-log, *printed every 30 seconds* : ""log.level": "WARN", "message":"This node is a fully-formed single-node cluster with cluster UUID [9Oz0OEfJSd-s52NYO3Etvw], but it is configured as if to discover other nodes and form a multi-node cluster via the [discovery.seed_hosts=[elasticsearch-01]] setting. Fully-formed clusters do not attempt to discover other nodes, and nodes with different cluster UUIDs cannot belong to the same cluster. The cluster UUID persists across restarts and can only be changed by deleting the contents of the node's data path(s). Remove the discovery configuration to suppress this message." Could we update the config to remove this warning please ?

**Comment by tomkralidis** [comment]
I've updated the PR to suppress the single node cluster and geoip warning messages.

For those wishing to avoid data loss on the wis2box API, the resulting migration would be:

```bash
python3 wis2box-ctl.py stop
vi docker-compose.yml  # upgrade elasticsearch from 7.16.2 to 7.17.0
python3 wis2box-ctl.py start
python3 wis2box-ctl.py stop
vi docker-compose.yml  # upgrade elasticsearch from 7.17.0 to 8.6.2
docker volume rm wis2box_project_api-config
python3 wis2box-ctl.py start
```

Else:
```bash
docker volume rm wis2box_project_es-data
docker volume rm wis2box_project_api-config
```

**Comment by tomkralidis** [comment]
Marking as WIP for the time being, to be implemented along with metadata UIs.

**Review by webb-ben — APPROVED** [review]

**Review by david-i-berry — COMMENTED** [review]
I've had a look over and nothing jumps out at me. I'll defer to @maaikelimper however for the approval..

**Review by maaikelimper — APPROVED** [review]
OK for me.

I note that we will need to review the correct steps to avoid data-loss when moving from 1.0b2 to 1.0b3 once the new release-candidate is prepared.

**Pull request merged**
