### PR TITLE
merge country and centre-id

### LINKED ISSUE #562: merge centre-id and country-id in topic-hierarchy
We need to adapt wis2box to use the new topic-hierarchy whereby country-id are centre-id are merged into a single level:
For example:
`orig/a/wis2/dza/alger_met_centre/data/core/weather/surface-based-observations/synop`
becomes:
`orig/a/wis2/dz-alger_met_centre/data/core/weather/surface-based-observations/synop`

At first glance I can see this will require updates in:
- wis2box/data/base.py
- wis2box/metadata/discovery.py
- .github/workflows/tests-docker.yml
- docs/
- test/data/metadata/
- tests/integration/
- test/data/data-mappings.xml
- examples/config
- wis2box-create-config.py
- config-templates/
- wis2box-ftp (separate repo)

Will this be considered a breaking change (all existing data to be purged as collections have to be recreated) or can we provide migration-script ?

### LINKED ISSUE #576: Publishing discovery metadata generated by wis2box-create-config.py results in "Error: 'name'"
After generating discovery metadata using wis2box-create-config.py and attempting to publish it:

wis2box metadata discovery publish /data/wis2box/metadata/discovery/metadata-synop.yml
Publishing discovery metadata from /data/wis2box/metadata/discovery/metadata-synop.yml
Error: 'name

The error can be addressed by replacing 'individualname: null' and providing a name.

I propose we update wis2box-create-config.py and the metadata templates to ensure a name is provided in this field

### PR DESCRIPTION
**Pull request by tomkralidis**
Fixes #562 

Fixes #576

Note: we are keeping `country` in the MCF `wis2box` object, mostly as a means to help users pre-select their country to derive a related bounding box.  If https://github.com/wmo-im/wis2box/blob/main/config-templates/countries.json is updated to be based on TLD (and not ISO 3166-3), then we can remove `country` entirely from the wis2box workflow (this can be part of another PR).

### CODE REVIEW

**Comment by tomkralidis** [comment]
TODO: update relevant screenshots (@maaikelimper)

**Comment by maaikelimper** [comment]
@tomkralidis  Could we please add some clarification on choosing the correct center-id in the documentation here:
https://github.com/wmo-im/wis2box/blob/31e57b86505570b6e9eedae8f769e2981d7f1574/docs/source/user/setup.rst?plain=1#L45-L46

Should the wis2box-create-config.py include a check that ensures the user provides a valid TLD prefix ?

**Comment by tomkralidis** [comment]
Note: we are keeping `country` in the MCF `wis2box` object, mostly as a means to help users pre-select their country to derive a related bounding box.  If https://github.com/wmo-im/wis2box/blob/main/config-templates/countries.json is updated to be based on TLD (and not ISO 3166-3), then we can remove `country` entirely from the wis2box workflow (this can be part of another PR).

As for guidance on centre id selection, suggest we defer until the WIS2 Guide is approved.

Having said this, I've pushed a small doc update to help clarify in the meantime.

**Review by maaikelimper — APPROVED** [review]
Thanks for the clarification, approved.

I will prepare a separate PR to update wis2box-create-config.py and countries.json

**Pull request merged**
