### PR TITLE
fix message publication for discovery metadata (#454)

### LINKED ISSUE #454: Problems with publishing metadata using wis2box
## User story
As a WIS2 node by using wis2box, I want to publish our country metadata message notifications via wis2box so that GDCs and GBs can subscribe our metadata message notification and/or download.

## Acceptance criteria

- [ ] acceptance criteria 1
According to wis2box documentation：
[](https://docs.wis2box.wis.wmo.int/en/latest/reference/running/api-publishing.html)
We use this command to publish our test metadata: 
**wis2box metadata discovery publish /path/to/discovery-metadata.yml**
By using MQTT Explorer, we successfully subscribe our metadata message notification **but it is different from the observation data message notification, may I ask whether it is correct and whether it meets the requirements?**

we found that by using MQTT Explorer, subscribing to France GB, some country who publish metadata message notification seems to conform to WIS2 node requirements (**like Germany[deu] metadata message notification**).
However, the metadata message notification we published through **wis2box(1.0b3)** seems too long and looks incorrect.
Could you pls give us some help and advice? Thank you very much.
## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

### PR DESCRIPTION
**Pull request by tomkralidis**
Fixes #454

### CODE REVIEW

**Comment by tomkralidis** [comment]
CI issues are likely unrelated and will be addressed in another PR as needed.

**Comment by tomkralidis** [comment]
Aside: when I run the integration tests locally against the test setup they pass as expected.

**Comment by tomkralidis** [comment]
](url)

**Comment by tomkralidis** [comment]
There are issues in the message validation that were bound to WNM schema updates (it worked for me locally given I had cached schemas on my local pywis-pubsub build [which is external to Docker per se for integration tests]).  As a result I will run CI here once https://github.com/wmo-im/pywis-pubsub/pull/25 is updated and a new pywis-pubsub version is released thereafter.

**Comment by tomkralidis** [comment]
pywis-pubsub 0.4.0 released, CI back to passing.

**Review by maaikelimper — APPROVED** [review]

**Pull request merged**
