### PR TITLE
packaging requires separate installation of python modules to support…

### PR DESCRIPTION
**Pull request by petersilva**
to use metpx-sr3 3.0.15 or later versions, dependencies for optional deatures must be manually installed.
This was formerly done with mandatory dependencies, which caused portability issues.

### CODE REVIEW

**Comment by petersilva** [comment]
ok rebase done...

**Comment by petersilva** [comment]
ok people are complaining about div/0 ... that was fixed in 3.0.15, but folks backed out of 3.0.15 rather than installing the missing dependency... and this branch doesn't fix it, because tom applied an explicit 3.0.14 version over the original patch which just added the dependencies.

**Comment by tomkralidis** [comment]
I think this has now been fixed as part of #163.

**Comment by tomkralidis** [comment]
Closing given updates in #163

**Pull request closed without merging**
