### PR TITLE
add pywis-pubsub PubSub utility

### PR DESCRIPTION
**Pull request by tomkralidis**
Addresses #187 and #14

### CODE REVIEW

**Review by maaikelimper — COMMENTED** [review]
I'm not sure why we should install pywis-pubsub in the wis2box-container. 
We can document how to use pywis-pubsub in our user guide but it can be run anywhere outside of the wis2box-container.

**Comment by tomkralidis** [comment]
Installing pywis-pubsub onto wis2box proper meets the download requirement which is a core requirement bound to 1.0.  There is also a note in the documentation which informs users that they can install pywis-pubsub beyond wis2box in external environment, including links to pywis-pubsub itself.

**Comment by maaikelimper** [comment]
The documentation you submitted suggest the user logins to the wis2box-container and run the subscriber from the command-line inside the box, which is not practical as a user would typically want to run this for a long/indefinite period of time.  
How about we add a (optional) docker-compose-download.yml in which we add a "wis2box-download"-service, which would just be a python-based Docker container with minimum requirements for running the "pywis-pubsub subscribe"-command ? This would cover the download-requirement to address #187 and #14 and would allow the user to run the download-feature independently.

**Comment by tomkralidis** [comment]
CI error is unrelated/intermittent.

**Comment by maaikelimper** [comment]
sorry for committing directly into your branch, I added my proposed changes in the docs and in the Dockerfile.

I added '--download' option in Dockerfile so that the files are downloaded by default when running the container.

**Review by maaikelimper — APPROVED** [review]

**Pull request merged**
