### PR TITLE
add username to cron.d (#240)

### PR DESCRIPTION
**Pull request by tomkralidis**
Addresses #240

### CODE REVIEW

**Comment by tomkralidis** [comment]
@maaikelimper can you validate?  The cron should be working.

**Review by maaikelimper — COMMENTED** [review]
It does not work these are the errors reported:
2022-10-12 19:00:01 | /bin/sh: 1: /bin/sh: 1: wis2box: not found
2022-10-12 19:00:01 | wis2box: not found

**Review by maaikelimper — APPROVED** [review]
approved with latest commit

**Comment by maaikelimper** [comment]
I've tested issue-240 branch by leaving it running overnight on wis2box-italy and  files were archived correctly at 01:00 UTC this morning:
image

**Pull request merged**
